services:
  remnanode:
    image: ${REMNAWAVE_NODE_IMAGE:-ghcr.io/astracat2022/rennawave-node-aesingflow:latest}
    container_name: remnanode
    hostname: remnanode
    network_mode: host
    restart: always
    cap_add:
      - NET_ADMIN
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    environment:
      - NODE_PORT=${NODE_PORT:-2222}
      - SECRET_KEY=${SECRET_KEY}
      - CUSTOM_CORE_URL=${CUSTOM_CORE_URL:-}
